apiVersion: v1
kind: Service
metadata:
  name: {{ include "thingsboard.fullname" . }}
  labels:
    {{- include "thingsboard.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 9090
      protocol: TCP
      name: http
    - port: 1883
      targetPort: 1883
      protocol: TCP
      name: mqtt
    - port: 5683
      targetPort: 5683
      protocol: UDP
      name: caop
  selector:
    app: thingsboard