apiVersion: v1
kind: Service
metadata:
  name: {{ include "thingsboard.fullname" . }}
  labels:
    {{- include "thingsboard.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 9090
      protocol: TCP
      name: http
  selector:
    app: thingsboard